-- DROP TABLE CUSTOMER;

CREATE TABLE IF NOT EXISTS CUSTOMER(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    GRADE VARCHAR(255),
    DEPARTMENT VARCHAR(255)
);


